Repository fernando-hidalgo/decide-part-murillo, pull requests merged in 2023-12, with the labels that each got.

#79 feat: Home base
  decide/decide/settings.py
  decide/decide/templates/home.html
  decide/decide/urls.py
  decide/decide/views.py
Labels: Visualización, MURILLO 1

#78 Feature/mrl31 postprocesado sainte lague
  decide/postproc/tests.py
  decide/postproc/views.py
Labels: Post-Procesado, MURILLO 2

#81 feature/MRL18-Votación por preferencia
  decide/store/models.py
  decide/store/tests.py
  decide/store/urls.py
  decide/store/views.py
Labels: Store, MURILLO 2

#82 Feature/mrl29 censo votacion si no
  decide/census/admin.py
  decide/census/migrations/0004_censusyesno.py
  decide/census/models.py
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
Labels: Censo, MURILLO 2

#84 Feature/mrl12 votacion si no bis
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/urls.py
  decide/store/views.py
  decide/voting/views.py
Labels: Votación, Store, MURILLO 2

#89 fix: eliminados imports sin uso de voting
  decide/voting/models.py
  decide/voting/tests.py
Labels: Votación, MURILLO 1

#86 Feature/mrl10 interfaz de votación por preferencia
  decide/booth/templates/booth/boothPreference.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/visualizer/templates/visualizer/visualizer_preference.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/admin.py
  decide/voting/models.py
Labels: Visualización, Votación, Cabina, MURILLO 2

#101 fix: Arreglado permisos votacion preferencia
  decide/store/views.py
Labels: Store, MURILLO 2

#102 Feature/mrl21 autentificacion correo
  decide/authentication/templates/register.html
  decide/authentication/tests.py
  decide/authentication/views.py
  loadtest/locustfile.py
Labels: Autenticación, MURILLO 2

#111 refactor: Trailing Whitespace eliminado
  decide/postproc/views.py
Labels: Post-Procesado, MURILLO 2

#108 test: Test de carga exportación de censo
  loadtest/locustfile.py
Labels: Censo, MURILLO 2

#115 fix: Arreglo postprocesado
  decide/booth/templates/booth/boothYesNo.html
  decide/voting/models.py
Labels: Votación, MURILLO 2

#119 feat: Preferencias unicas en votación
  decide/booth/templates/booth/boothPreference.html
Labels: Cabina, MURILLO 2

#112 Hotfix/census errors groups
  decide/census/admin.py
  decide/census/migrations/0005_alter_census_unique_together_and_more.py
  decide/census/models.py
  decide/census/tests.py
  decide/census/views.py
Labels: Hotfix, MURILLO 1

#127 Feature/mrl07 frontend censo
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/census/serializers.py
  decide/census/templates/census/admin_census.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/voting/models.py
Labels: Censo, MURILLO 1

#120 feat: Mensaje error si inicio sesión mal
  decide/authentication/templates/login.html
  decide/authentication/views.py
Labels: Autenticación, MURILLO 1

#129 Feature/mrl44 visualizer votacion yesno
  decide/visualizer/templates/visualizer/visualizerYesNo.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: Visualización, MURILLO 2

#136 Smart jobs config bis
  .github/workflows/smart-test.yml
Labels: Config, MURILLO 2

#130 feat: Atributo mixnetId para votación yes no
  decide/voting/migrations/0009_votingyesno_mixnet_id.py
  decide/voting/models.py
Labels: Votación, Mixnet

#135 Feature/mrl40 cambio en el reparto de escaños en votación por preferencia
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/voting/models.py
Labels: Votación, Post-Procesado, MURILLO 2

#140 feat: Creado mixnet votacion preferencia
  decide/voting/migrations/0010_votingbypreference_mixnet_id.py
  decide/voting/models.py
Labels: Votación, MURILLO 2, Mixnet

#139 ci: Automatización de imágenes de Docker
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: Config, MURILLO 2

#149 feat: Creado mixnet votacion basica
  decide/voting/migrations/0011_voting_mixnet_id.py
  decide/voting/models.py
Labels: Votación, MURILLO 2, Mixnet

#150 Feature/mrl51 correo aviso censo
  decide/census/models.py
  decide/census/templates/census/aviso.html
  decide/decide/settings.py
Labels: Censo, MURILLO 2

#143 Feature/mrl41 votacion opcion multiple
  decide/census/admin.py
  decide/census/migrations/0006_censusmultichoice.py
  decide/census/models.py
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/store/admin.py
  decide/store/migrations/0006_votemultichoice.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/urls.py
  decide/store/views.py
  decide/voting/admin.py
  decide/voting/migrations/0009_questionmultichoice_votingmultichoice_and_more.py
  decide/voting/migrations/0010_questionoptionmultichoice_multichoice_and_more.py
  decide/voting/migrations/0011_merge_20231215_1206.py
  decide/voting/migrations/0012_merge_0011_merge_20231215_1206_0011_voting_mixnet_id.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: Censo, Votación, Store, MURILLO 1

#151 Feature/MRL11 - Interfaz traducible, en Español y otros idiomas
  decide/decide/settings.py
  decide/locale/en/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.po
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/templates/visualizer/visualizerYesNo.html
  decide/visualizer/templates/visualizer/visualizer_preference.html
  requirements.txt
Labels: Visualización, Traducción, MURILLO 1

#156 Feature/mrl54 traduccion nuevo frontend
  decide/decide/templates/home.html
  decide/locale/en/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.po
Labels: Visualización, Traducción, MURILLO 1

#154 test: Test de carga Booth
  loadtest/locustfile.py
Labels: Cabina, MURILLO 2

#161 fix: Arreglo visualizacion de votos por preferencia
  decide/visualizer/templates/visualizer/visualizer_preference.html
Labels: Visualización, MURILLO 2

#162 Feature/mrl58 traduccion admin exp censo
  decide/booth/templates/booth/booth.html
  decide/booth/templates/booth/boothPreference.html
  decide/booth/templates/booth/boothYesNo.html
  decide/census/templates/census/admin_census.html
  decide/census/templates/census/aviso.html
  decide/census/templates/census/import_census.html
  decide/locale/en/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.po
Labels: Visualización, Traducción, MURILLO 1

#164 Feature/mrl46 test para booth de yesno
  decide/booth/tests.py
Labels: Cabina, MURILLO 2

#165 Feature/mrl52 creacion interfaz para votaciones de multiples opciones (booth)
  decide/booth/templates/booth/boothMultiChoice.html
  decide/booth/urls.py
  decide/booth/views.py
Labels: Cabina, MURILLO 2

#169 feat/MRL62 - Traducción de módulos en admin
  decide/base/models.py
  decide/census/models.py
  decide/locale/en/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.po
  decide/store/models.py
  decide/voting/models.py
Labels: Visualización, Traducción, MURILLO 1

#171 Feature/mrl60 aumento coverage
  decide/census/tests.py
  decide/visualizer/tests.py
Labels: Censo, Visualización, MURILLO 1

#167 Feature/mrl57 test carga store
  loadtest/gen_census_multichoice.py
  loadtest/gen_census_preference.py
  loadtest/gen_census_yesno.py
  loadtest/locustfile.py
Labels: Store, MURILLO 2

#172 feat: Añadido mixnet id a voting multi choices
  decide/voting/migrations/0013_alter_question_options_and_more.py
  decide/voting/models.py
Labels: Votación, MURILLO 2, Mixnet

#173 Feature/mrl61 creacion interfaz votacion multiples opciones visualizer bis
  decide/base/migrations/0004_alter_auth_options_alter_key_options.py
  decide/booth/tests.py
  decide/census/migrations/0007_alter_census_options_and_more.py
  decide/store/migrations/0007_alter_vote_options_alter_votebypreference_options_and_more.py
  decide/store/views.py
  decide/visualizer/templates/visualizer/visualizerMultiChoice.html
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/migrations/0013_alter_question_options_and_more.py
  decide/voting/migrations/0014_remove_questionoptionmultichoice_selected.py
  decide/voting/migrations/0015_questionoptionmultichoice_selected.py
  decide/voting/models.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: Visualización, MURILLO 2

#174 Feature/mrl36 logout de usuario
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/decide/templates/home.html
Labels: Autenticación, MURILLO 2
