Repository fernando-hidalgo/decide-part-murillo, pull requests merged in 2023-11, with the labels that each got.

#31 feat: Feature/mrl04 reusar censo
  decide/census/admin.py
  decide/census/tests.py
  decide/decide/settings.py
Labels: Censo

#32 feat: Feature/mrl23 exportar resultados votacion
  decide/voting/admin.py
  decide/voting/tests.py
Labels: Votación

#34 feat: Feature/mrl03 importar exportar censo
  decide/census/admin.py
  decide/census/templates/census/import_census.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  requirements.txt
Labels: Censo

#36 feat: Pintado de gráficas de los votos y censo
  decide/visualizer/templates/visualizer/visualizer.html
Labels: Visualización

#46 fix: Edición de voto
  decide/booth/templates/booth/booth.html
Labels: Hotfix

#38 Feature/mrl14 aplicar ley dhont
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/voting/migrations/0005_voting_escaños_voting_tallytype.py
  decide/voting/models.py
Labels: Post-Procesado

#47 fix: Test Traducciones deshabilitado
  decide/visualizer/tests.py
Labels: Hotfix

#53 feat: Vagrant
  vagrant/Vagrantfile
  vagrant/django.yml
  vagrant/files/settings.py
  vagrant/packages.yml
  vagrant/python.yml
Labels: Config, MURILLO 1

#43 Feature/MRL15 Registro Usuarios
  decide/authentication/models.py
  decide/authentication/templates/register.html
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/views.py
  loadtest/locustfile.py
Labels: Autenticación, MURILLO 2

#61 chore: Cambio de versiones de python para actions
  .github/workflows/django.yml
Labels: Config

#68 Feature/mrl18 votación por preferencia bis
  decide/store/admin.py
  decide/store/migrations/0004_votebypreference.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/urls.py
  decide/store/views.py
  decide/voting/admin.py
  decide/voting/migrations/0006_questionbypreference_votingbypreference_and_more.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: Votación, Store, MURILLO 2

#75 Feature/mrl13 grupos en censo
  decide/census/admin.py
  decide/census/migrations/0002_census_group.py
  decide/census/models.py
Labels: Censo, MURILLO 2
